#!/bin/sh
# Copyright 2020 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,

set -e

libpath=${APPDIR}/masterpdfeditor
dirname=${APPDIR}/masterpdfeditor

LD_LIBRARY_PATH=${APPDIR}/lib:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=${APPDIR}/platforms:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=${APPDIR}/printsupport:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=${APPDIR}/iconengines:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=${APPDIR}/imageformats:${LD_LIBRARY_PATH}
LD_LIBRARY_PATH=${APPDIR}/platformthemes:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}

cd ${OWD}

ls -lah ${APPDIR}/masterpdfeditor*.sh > /dev/null 2>&1 && exec ${APPDIR}/masterpdfeditor*.sh "$@"
ls -lah ${APPDIR}/masterpdfeditor* > /dev/null 2>&1 && exec ${APPDIR}/masterpdfeditor* "$@"
