# Copyright 2020 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
PWD:=$(shell pwd)

.PHONY: all

all: clean init

	mkdir --parents $(PWD)/build/Boilerplate.AppDir/mpe
	$(PWD)/bin/Apprepo.AppImage --destination=$(PWD)/build appdir boilerplate libatk1.0-0

	# Check download links here: 
	# https://code-industry.net/free-pdf-editor/

	wget --output-document=$(PWD)/build/build.deb https://code-industry.net/public/master-pdf-editor-5.8.70-qt5_included.x86_64.deb
	dpkg -x $(PWD)/build/build.deb $(PWD)/build
	
	cp --force --recursive $(PWD)/build/opt/master-pdf-editor*/* $(PWD)/build/Boilerplate.AppDir/mpe

	rm -f $(PWD)/build/Boilerplate.AppDir/mpe/*.desktop 		|| true
	rm -f $(PWD)/build/Boilerplate.AppDir/mpe/*.png 		  	|| true
	rm -f $(PWD)/build/Boilerplate.AppDir/mpe/*.svg 		  	|| true
	rm -f $(PWD)/build/Boilerplate.AppDir/mpe/*.jpg 		  	|| true
	rm -f $(PWD)/build/Boilerplate.AppDir/mpe/*.sh 		  	    || true

	echo ''                                                    >> $(PWD)/build/Boilerplate.AppDir/AppRun
	echo ''                                                    >> $(PWD)/build/Boilerplate.AppDir/AppRun
	echo 'LD_LIBRARY_PATH=$${LD_LIBRARY_PATH}:$${APPDIR}/mpe'  >> $(PWD)/build/Boilerplate.AppDir/AppRun
	echo 'export LD_LIBRARY_PATH=$${LD_LIBRARY_PATH}'          >> $(PWD)/build/Boilerplate.AppDir/AppRun
	echo ''                                                    >> $(PWD)/build/Boilerplate.AppDir/AppRun
	echo ''                                                    >> $(PWD)/build/Boilerplate.AppDir/AppRun
	echo 'exec $${APPDIR}/mpe/masterpdfeditor*    "$${@}"'     >> $(PWD)/build/Boilerplate.AppDir/AppRun

	rm -f $(PWD)/build/Boilerplate.AppDir/*.desktop 		|| true
	rm -f $(PWD)/build/Boilerplate.AppDir/*.png 		  	|| true
	rm -f $(PWD)/build/Boilerplate.AppDir/*.svg 		  	|| true
	rm -f $(PWD)/build/Boilerplate.AppDir/*.jpg 		  	|| true

	cp --force $(PWD)/AppDir/*.svg 		  	$(PWD)/build/Boilerplate.AppDir 			|| true
	cp --force $(PWD)/AppDir/*.desktop 		$(PWD)/build/Boilerplate.AppDir 			|| true
	cp --force $(PWD)/AppDir/*.png 		  	$(PWD)/build/Boilerplate.AppDir 			|| true

	chmod +x $(PWD)/build/Boilerplate.AppDir/AppRun

	export ARCH=x86_64 && $(PWD)/bin/appimagetool.AppImage $(PWD)/build/Boilerplate.AppDir $(PWD)/MasterPDFEditor.AppImage
	chmod +x $(PWD)/MasterPDFEditor.AppImage

init:
	mkdir --parents $(PWD)/bin

	wget https://apprepo.de/appimage/download/apprepo \
		--output-document=$(PWD)/bin/Apprepo.AppImage
	chmod +x $(PWD)/bin/Apprepo.AppImage

	wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage \
		--output-document=$(PWD)/bin/appimagetool.AppImage
	chmod +x $(PWD)/bin/appimagetool.AppImage

clean:
	rm -rf $(PWD)/*.AppImage
	rm -rf $(PWD)/bin/*
	rm -rf $(PWD)/build
